### ISSUE TITLE
GeoFeatureModelSerializer

### ISSUE THREAD

**Issue by cfdbwrbq** [MattBroach/DjangoRestMultipleModels#52]
Hi! Thanks for application)
[GeoFeatureModelSerializer](https://github.com/openwisp/django-rest-framework-gis/blob/7031286673d82988098d14abca76d1cd11c79a75/rest_framework_gis/serializers.py#L37) from [rest_framework_gis ](https://github.com/openwisp/django-rest-framework-gis) + FlatMultipleModelAPIViewSet

```
from rest_framework import serializers
class DataSerializer(serializers.ModelSerializer):

     class Meta:
        model = Data
        fields = ('__all__')

from rest_framework_gis.serializers import GeoFeatureModelSerializer

class PoiSerializer(GeoFeatureModelSerializer):
    class Meta:
        model = Poi
        geo_field  = "geom"
        fields = ('__all__')
    
    def to_representation(self, instance):
        ret = super(PoiSerializer, self).to_representation(instance)
        if ret.get('geometry'):
            ret['geometry'].update({'crs': {"type": "name", "properties": {"name": "EPSG:404000"}}})
        return ret
```
```
class TextAPIView(FlatMultipleModelAPIViewSet):
    querylist = [
        {'queryset': Poi.objects.all(), 'serializer_class': PoiSerializer}, # GeoFeatureModelSerializer - internal server error
        {'queryset': Data.objects.all(), 'serializer_class': dataSerializer}, # ModelSerializer - works ok
    ]
```
fails
```
Traceback (most recent call last):
  File "/home/admin/gis/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/admin/gis/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/admin/gis/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/admin/gis/env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/admin/gis/env/lib/python3.6/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/admin/gis/env/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/admin/gis/env/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/admin/gis/env/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/admin/gis/env/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/admin/gis/env/lib/python3.6/site-packages/drf_multiple_model/mixins.py", line 117, in list
    results = self.add_to_results(data, label, results)
  File "/home/admin/gis/env/lib/python3.6/site-packages/drf_multiple_model/mixins.py", line 216, in add_to_results
    datum.update({'type': label})
AttributeError: 'str' object has no attribute 'update'
```
it's a django-rest-framework-gis' serializer problem?

**Comment by MattBroach** [comment]
Unfortunately interaction with other third-party libraries is a bit beyond the scope of this project.  Looking at the error, however, my guess is that the `GeoFeatureModelSerializer` is returning a list of strings, rather than a list of objects, which is .. strange behavior for a serializer.  I'd look at what that serializer is doing.
